server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/configurations  # Ruta donde se buscarán los archivos de configuración
