spring:
  application:
    name: EcommerceMicroservice
  datasource:
    url: jdbc:mysql://ecommerce-db.crec20oc0bfb.us-east-2.rds.amazonaws.com:3306/ecommerce
    username: admin
    password: Ecommerce1234*
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8086

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
