server:
  port: 8761

spring:
  application:
    name: EcommerceEureka
  #Desactivar Spring Cloud Config
  cloud:
    config:
      enabled: false
eureka:
  instance:
    hostname: ecommerce-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
