#App Config
server:
  port: 8080

spring:
  application:
    name: EcommerceGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice
          uri: lb://EcommerceMicroservice
          predicates:
            -  Path=/**
    #Desactivar Spring Cloud Config
    config:
      enabled: false

eureka:
  instance:
    hostname: ecommerce-gateway
  client:
    service-url:
      defaultZone: http://ecommerce-eureka:8761/eureka
    register-with-eureka: true
    fetch-registry: true
